config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :costumes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  delete "bookings/:id", to: "bookings#destroy", as: :bye_booking
  get "my_booking", to: "bookings#my_booking"
  get "my_costume", to: "costumes#my_costume"
  post "bookings/:id/accept", to: "bookings#accept", as: :accept_booking
  post "bookings/:id/decline", to: "bookings#decline", as: :decline_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :costume

  # validates :start_date, presence: true
  # validates :end_date, presence: true
end

app/models/costume.rb
class Costume < ApplicationRecord
  CATEGORY = %w[Halloween Folk Christmas Party Fancy Carnival Animal Fantasy]
  SIZE = %w[XS(4) S(8) M(12) L(16) XL(20) XXL(22)]
  belongs_to :user
  has_many :bookings

  include PgSearch::Model
  pg_search_scope :search_by_name_size_and_category,
  against: [ :name, :size, :category ],
  using: {
    tsearch: { prefix: true }
  }

  # validates :price, :description, :size, :photo_url, presence: true
  # validates :name, presence: true, length: { minimum: 3 }
  # validates :category, presence: true, inclusion: { in: CATEGORY }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :costumes

  # validates :first_name, :last_name, :email, presence: true
  # validates :email, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  # def after_sign_out_path_for(*)
  #   redirect_to root_path
  #   # request.referrer
  # end

  def after_sign_out_path_for(resource)
    # home
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_costume, only: [:new, :create]
  before_action :set_booking, only: [:accept, :decline, :destroy!]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.costume = @costume
    @booking.user = current_user
    flash[:notice] = @booking.errors.full_messages.to_sentence unless @booking.save
    redirect_to my_booking_path
  end

  def my_booking
    # to get the bookings that I am renting from other users
    @bookings = Booking.where(user_id: current_user.id)
    # raise
    @my_costume_bookings = Booking.where(costume_id: Costume.where(user: current_user))
    # raise
  end

  def accept
    @booking.accepted = "Accepted"
    @booking.save
    redirect_to my_booking_path, status: :see_other
  end

  def decline
    @booking.accepted = "Declined"
    @booking.save
    redirect_to my_booking_path, status: :see_other
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to my_booking_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_costume
    @costume = Costume.find(params[:costume_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end
# costume.user not user.booking

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_costume, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      # @results = PgSearch.multisearch(params[:query])
      # @costumes = []
      # @results.each do |result|
      #   @costumes << result.searchable
      # end
      # raise
    @costumes = Costume.search_by_name_size_and_category(params[:query])
    else
      @costumes = Costume.order(created_at: :desc)
    end
  end

  def new
    @costume = Costume.new
  end

  def edit
  end

  def create
    @costume = Costume.new(costume_params)
    @costume.user_id = current_user.id
    @costume.save
    redirect_to costume_path(@costume)
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end

  def update
    if @costume.update(costume_params)
      redirect_to @costume
    else
      render :edit
    end
  end

  def show
    @booking = Booking.new
  end

  def destroy
    @costume.destroy
    redirect_to costumes_path, status: :see_other
  end

  def my_costume
    @costumes = Costume.where(user_id: current_user.id)
  end

  private

  def costume_params
    params.require(:costume).permit(:name, :price, :description, :size, :category, :photo_url)
  end

  def set_costume
    @costume = Costume.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #   root to: "users#home"
 def home
  @costumes = Costume.all
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_booking.html.erb
<% if @bookings.blank? == false %>

  <div class = "center">
  <div class="index-container">
  <h1 class="p-4" >Your Bookings</h1>

  <div class="card-container">
  <% @bookings.each do |booking| %>
    <div class = "card p-2">
      <div class="card-item-image">
      <%= link_to costume_path(booking.costume[:id]) do %>
        <%= image_tag(booking.costume.photo_url) %>
        <% end %>
      </div>
        <h3><%= booking.costume.name %></h3>
        <% if booking.accepted == "pending" %>
          <h5 class="pending-booking-user"><strong>Status: </strong><%= image_tag "hourglass.png", style: "width:25px; height:25px; margin:5px" %> pending...</h5>
         <% elsif booking.accepted == "Accepted" %>
          <h5 class="pending-booking-user"><strong>Status: </strong><%= image_tag "accepted.png", style: "width:28px; height:28px; margin:5px" %> Accepted!</h5>
         <% elsif booking.accepted == "Declined" %>
          <h5 class="pending-booking-user"><strong>Status: </strong><%= image_tag "declined.png", style: "width:28px; height:28px; margin:5px" %> Declined</h5>
         <% end %>
        <div class="d-flex justify-content-between align-items-center">
          <h4>£<%= booking.costume.price.round %> per day</h4>

          <%= link_to bye_booking_path(booking.id), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" } do %>
          <%= image_tag "trashcan.png", style: "width:28px; height:28px; margin:5px" %>
          <% end %>
        </div>
      </div>
      <%# <i class="fa-solid fa-trash-can"></i> %>
      <%# <%= link_to my_booking_path(@booking), class: "btn book-btn" %>
      <%# <i class="fa-solid fa-trash-can">
      <% end %>
    <% end %>
  </div>


  <% elsif @bookings.blank? == true %>
  <div class = "center">
    <h1 class="p-4" >Your Bookings</h1>
    <div class="no-bookings-yet mt-5" style="text-align:center">
      <p style="text-align:center; color: RGB(100, 91, 85)">No bookings yet!</p>
      <%= link_to costumes_path do %>
        <%= image_tag "booking.png", style:"width: 60px; height: 60px; opacity: 0.7 " %>
        <% end %>
    </div>
  </div>
  <% end %>
<br>
<br>
<br>
<br>
<br>


<hr>


<% if @my_costume_bookings.blank? == false %>
<div class = "center">
  <div class="index-container">
  <h1 class="p-4" >Your Costumes Bookings</h1>


    <div class="card-container">
    <% @my_costume_bookings.each do |booking| %>
      <div class = "card">
        <div class="card-item-image">
        <%= link_to costume_path(booking.costume[:id]) do %>
          <%= image_tag(booking.costume.photo_url) %>
          <% end %>
        </div>

          <h5 class="pending-booking-user" style="text-align: center"><strong>Booking made by:</strong> <%= booking.user.email %></h5>
          <%if booking.accepted == "pending"%>
          <div class="d-flex justify-content-center">
            <%= link_to accept_booking_path(booking), data: {turbo_method: :post} do %>
            <%= image_tag "accept.png", class: "decision-button", style: "width:40px; height:40px; margin:5px"  %>
            <% end %>
            <%= link_to decline_booking_path(booking), data: {turbo_method: :post} do %>
            <%= image_tag "decline.png", class: "decision-button", style: "width:40px; height:40px; margin:5px" %>
            <% end %>
          </div>

          <% elsif booking.accepted == "accepted" || "declined" %>
            <h6><%= booking.accepted.capitalize %></h6>
          <% end %>
      </div>
    <% end %>
    <% elsif @my_costume_bookings.blank? == true %>
    <div class = "center">
    <h1 class="p-4" >Your Costumes Bookings</h1>
    <div class="no-bookings-yet mt-5" style="text-align:center">
      <p style="text-align:center; color: RGB(100, 91, 85)">No one booked any of your costumes yet!</p>
        <%= image_tag "sad.png", style:"width: 60px; height: 60px; opacity: 0.7", class: "mb-4" %>
    </div>
  </div>
    <% end %>
  </div>
  </div>
  </div>
  </div>
  </div>

app/views/costumes/edit.html.erb
<div class="body-center new-costume">
  <h1>Edit your costume</h1>
  <br>
  <%= simple_form_for @costume do |f| %>
    <%= f.input :name, placeholder: "Name" %>
    <%= f.input :price, placeholder: "Price" %>
    <%= f.input :description, placeholder: "Description" %>
    <%= f.input :size, placeholder: "Size" %>
    <%= f.input :category, collection: Costume::CATEGORY %>
    <%= f.input :photo_url, placeholder: "Photo URL" %>
    <%= f.submit class: "submit-btn" %>
  <% end %>
  <br>
</div>

app/views/costumes/index.html.erb
  <div class = "center">
  <div class="index-container">
  <h1 class="p-4" >Find a costume!</h1>


 <%= render 'shared/card_all' %>


</div>
</div>

app/views/costumes/my_costume.html.erb
<% if @costumes.blank? == true %>
<div class = "center">
    <div class="index-container">
    <h1 class="p-4">Costumes</h1>
    <p style="text-align:center; color: RGB(100, 91, 85); padding-top: 90px">You don't have any Costume added!</p>
  <%= link_to costumes_path do %>
  <%= image_tag "outfit.png", style:"width: 70px; height: 70px; opacity: 0.8 " %>
  <% end %>
  </div>
  </div>
<% elsif @costumes.blank? == false %>
    <div class = "center">
    <div class="index-container">
    <h1 class="p-4">Costumes</h1>
    <div class="card-container">
    <% @costumes.each do |costume| %>
      <div class = "card">
        <div class="card-item-image">
        <%= link_to costume_path(costume[:id]) do %>
          <%= image_tag(costume.photo_url) %>
        <% end %>
        </div>
          <h3><%= costume.name %></h3>
          <p class="mb-0">Size: <%= costume.size %></p>

        <div class="d-flex justify-content-between align-items-center">
          <h4>£<%= costume.price.round %> per day</h4>

          <%= link_to costume_path(costume[:id]), method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this costume?" } do %>
          <%= image_tag ("trashcan.png"), style: "width:28px; height:28px; margin:5px" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  </div>
  </div>
<% end %>

app/views/costumes/new.html.erb
<div class="body-center new-costume">
  <h1>Add a new costume</h1>
  <br>
  <%= simple_form_for @costume do |f| %>
    <%= f.input :name, placeholder: "Name" %>
    <%= f.input :price, placeholder: "Price(£)" %>
    <%= f.input :description, placeholder: "Description" %>
    <%= f.input :size, placeholder: "Size", collection: Costume::SIZE%>
    <%= f.input :category, collection: Costume::CATEGORY %>
    <%= f.input :photo_url, placeholder: "Photo URL" %>
    <%= f.submit class: " btn submit-btn" %>
  <% end %>
  <br>
</div>

app/views/costumes/show.html.erb
<div class = "show-container">
  <div class="row">
    <div class="col-12 col-md-6">
      <br>
      <div class="img-container">
        <%= image_tag @costume.photo_url %>
      </div>
      <br>
      <br>
      <br>
    </div>

    <div class="col-12 col-md-6">
      <div class = "description">
        <h2><%= @costume.name %></h2>
        <hr>
        <h4> Description: </h4>
          <p><%= @costume.description %></p>
        <h4> Category: </h4>
          <p><%= @costume.category %></p>
        <h4> Size: </h4>
          <p><%= @costume.size %></p>

      <br>
      <br>
      <% if current_user == @costume.user %>
        <div>
          <div class="booking-container" id='booking-btns'>
              <%= link_to "Edit this costume", edit_costume_path(@costume), class: " btn book-btn" %>
              <hr>
              <%= link_to "Delete this costume", costume_path(@costume), class: "btn book-btn", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this costume?" } %>
          </div>
        </div>
      <br>
      <br>
      <% else %>
        <div>
          <div class="booking-container" id='booking-btns' style="width: 40vw">
            <h2>Rent this costume from <strong>£<%= @costume.price.round %>/day</strong></h2>
            <br>
            <div class="simple_form">
              <%= simple_form_for [@costume, @booking] do |f| %>
                <%= f.input :start_date, html5: true %>
                <%= f.input :end_date, html5: true %>
                <br>
                <hr>
                <p>Price £<%= @costume.price.round  %> per day</p>
                <%= f.button :submit, value: "Book now", class: "book-btn" %>
              <% end %>
            </div>
          </div>
        <br>
        <br>
        </div>
      <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overdressed</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="wrapper">
   <%= render 'shared/navbar' %>
      <%= yield %>

      <div class="push"></div>
    </div>
        <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<html>

<head>

<title>Overdressed</title>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

<section class="banner body-center">
  <img src = "https://res.cloudinary.com/dpjxlsdtk/image/upload/v1653996934/costume_homepage_mjs2p1.png" class = "banner-img">

   <h1>Rent all the best costumes</h1>

  <%# <form action = "/" method = "GET" class = "form">
    <input type="text" placeholder="What are you searching for today?" class = "search-field">
    <button type="submit" class = "search-button"><i class="fa fa-search"></i></button>
  </form> %>

  <%= form_tag costumes_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "search-field",
      placeholder: "What are you searching for today?"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</section>

<section>
<div class="arrow_container">
    <a href="#scroll-target">
  <div class="chevron"></div>
  <div class="chevron"></div>
  <div class="chevron"></div>
  <span class="text-arrow" id="toscroll"></span>
    </a>
</div>
</section>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<section class = "featured-cards body-center" id="scroll-target">
  <h2> Featured <h2>


  <div class = "featured-sub-items-cards">
  <div class = "card-container">
   <%= render 'shared/card_featured' %>
    </div>

    </div>
    <%= link_to "Explore all", costumes_path, class: "explore-btn" %>
</section>



<br>
<br>
<br>
<br>
<br>
<br>
<br>

<section class="featured-items body-center">
<h2>We're giving costumes<br>a second chance</h2>
<br>
<br>
<p>We're taking costumes for a ride. With thousands of single-use costumes being thrown out every year,<br>we're making it our business to
undo what it started, one rental at a time.</p>
</section>


</body>
</html>

app/views/pages/index.html.erb
<h1> hello world </h1>

app/views/shared/_card_all.html.erb
  <div class="card-container">
  <% @costumes.each do |costume| %>
    <div class = "card">
      <div class="card-item-image">
      <%= link_to costume_path(costume[:id]) do %>
        <%= image_tag(costume.photo_url) %>
      <% end %>
      </div>
         <p>Size: <%= costume.size %></p>
        <h3><%=link_to costume.name, costume_path(costume[:id])%></h3>
        <h4><strong>Rent</strong> from £<%= costume.price.round %> per day</h4>
    </div>
  <% end %>
</div>

app/views/shared/_card_featured.html.erb
  <div class="card-container">
  <% @costumes.first(4).each do |costume| %>
    <div class = "card">
      <div class="card-item-image">
        <%= link_to costume_path(costume[:id]) do %>
        <%= image_tag(costume.photo_url) %>
        <% end %>
      </div>
         <p>Size: <%= costume.size %> </p>
        <h3><%=link_to costume.name, costume_path(costume[:id])%></h3>
        <h4><strong>Rent</strong> from £<%= costume.price.round %></h4>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
<%= link_to "OVERDRESSED", root_path, class: "logo-footer" %>
      <div class="footer-copyright">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
    </div>

app/views/shared/_navbar.html.erb
   <div class="navbar">
    <%= link_to "OVERDRESSED", root_path, class: "logo" %>
    <% if user_signed_in? %>
        <%= form_tag costumes_path, method: :get, class: "searchbar" do %>
          <button type="submit" class = "search-button"><i class="fa fa-search"></i></button>
          <%= text_field_tag :query,
          params[:query],
          class: "search-field",
          placeholder: "What are you searching for today?"
          %>
        <% end %>
      <div class="sign-up">
          <li class="m-1">
            <%= link_to "All Costumes", costumes_path, class: "nav-item2 active" %>
          </li>
          <li class="m-1">
            <%= link_to " + Add a Costume", new_costume_path, class: "nav-item2 active" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end mt-2" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", my_booking_path, class: "dropdown-item" %>
              <%= link_to "My Costumes", my_costume_path, class: "dropdown-item border-top" %>
              <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete}, class: "dropdown-item border-top"  %>
            </div>
          </li>
      </div>
    <% else %>
      <ul class="sign-up">
          <li>
              <%= link_to "Sign up", new_user_registration_path, class: "nav-item1 active" %>
          </li>
          <li>
            <%= link_to "Log in", new_user_session_path, class: "nav-item2" %>
          </li>
      </ul>
    <% end %>
    </div>